### ISSUE TITLE
File milestone and tickets for 0.5.0 release

### ISSUE THREAD

**Issue by carnesen** [carnesen/cli#56]
- [x] Write up "Features" in readme.md
- [x] Fill out "Structure" in readme.md
- [x] Write examples/readme.md
- [x] ValuedParser --> ArgGroup : https://github.com/carnesen/cli/pull/58
- [x] Close alwayscli issues
- [x] Contact dependents and offer upgrade assistance

**Comment by carnesen** [comment]
All tickets above have been filed under https://github.com/carnesen/cli/milestone/1
